pipeline:
  build:
    image: node:6.9.5
    commands:
      - npm install -g grunt-cli
      - apt-get update && apt-get install sendmail -y python make g++
    when:
      branch: [master]
  test:
    image: node:6.9.5
    commands:
       - grunt coverage
    when:
     branch: [master]   
services:
  database:
    image: mongo:3.2
