pipeline:
  build:
    image: node:6.9.5
    commands:
      - npm install -g grunt-cli
      - apt-get update && apt-get install -y g++-4.8 sendmail python make g++
      - grunt coverage
    when:
      branch: [master] 
services:
  database:
    image: mongo:3.2
